Отказ в обслуживании в Python SimpleXMLRPCServer Python 2.7.2Python 3.2.2 Описание: Уязвимость позволяет злоумышленнику произвести DoS атаку. Уязвимость существует из-за недостаточной обработки входных данных. Удаленный пользователь может произвести DoS атаку. URL производителя: http://www.python.org/ Решение: Для устранения уязвимости установите исправление с сайта производителя. Ссылки: https://bugzilla.redhat.com/show_bug.cgi?id=789790 http://bugs.python.org/issue14001 Журнал изменений: 12.04.2012 Внесено изменение в секцию "Наличие исправления".